### ISSUE TITLE
heatmap

### ISSUE THREAD

**Issue by rbxb** [BenWiederhake/pixelcrush#1]
It would be cool if you could see a heatmap of which pixels are the most difficult to overwrite by showing the value of the hashes normalized to the largest value. 

.../heatmap.png

**Comment by BenWiederhake** [comment]
I've been also thinking about that, but it might invite people to draw on this heatmap. Come to think of it, I don't recall why I thought this would be a bad thing. :)

**Comment by BenWiederhake** [comment]
[Done!](https://gebirge.uber.space/heatmap.png) :)
